#' ---
#' title: "Cleaning up port information for subsequent scripts"
#' author: "Paul Czechowski"
#' date: "September 1st, 2017"
#' output: pdf_document
#' toc: true
#' highlight: zenburn
#' ---
#'
#' # Preface
#' 
#' This scripts reads in inventory and port data files, removes superflous
#' columns, sets columns types. This script is derived from
#' `/Users/paul/Box Sync/CU_NIS-WRAPS/170912_code_r/170830_10_cleanup_tables.R`,
#' and was revised to accomodate newly formatted port data from the "Data
#' bootcamp" shortly before the 30th of August 2017. This script can be rendered by
#' calling `rmarkdown::render ("/Users/paul/Documents/CU_combined/Github/500_10_gather_predictor_tables.R")`.
#'
#' **WARNING:** This script reads in data mainly from "Dropbox" and "Box"
#' (see path names), which may have changed
#' since last script call. Both folders are version controlled, and the used 
#' commit are `9c6515d7b13a8cc7f5c9d853c268c46dc50059a7` and 
#' `dec809083d9b20507c3dde967bc4134215034afc`, respectively. Input and output 
#' data are stored as `.Rdata` files, so check these if the 
#' Dropbox data has changes. **Do not run this script** again, if you
#' do not want to overwrite the files this script produces.
#'
#' # Environment preparations
#' 
#' ## Flush environment
#'
rm(list=ls()) # for safety only

#'
#' ## Load package(s) 
library (tidyverse) # sorting and file handling
library (readxl)    # file handling

#'
#' ## Function definitions
#'
#' ### Reading file contents minding extensions
#' 
#' Data frames ("tibbles") are returned.
get_contents <- function (fnames = NULL) {
  print (fnames)
  if (grepl ("\\.xlsx$", fnames)) {
    message ("reading in '.xlsx' file: ", fnames)
    content <- read_excel (fnames) # https://www.rdocumentation.org/packages/readxl/versions/0.1.1/topics/read_excel
    }
  if (grepl("\\.csv$", fnames)) {
    message ("reading in '.csv' file:", fnames)
    content <- read_csv (fnames)   # see http://readr.tidyverse.org/reference/read_delim.html
    }
  return (content)
  }

#'
#' # Reading in data
#'
#' ## Define data sources  
#'
#' Define list of files to be read in 
#'
#' * Sample inventory (last updated 30.08.2017 - in version tracked repository)
#' * Climate info for 6651 ports - derivative of Keller et al. 2010 (being updated on or after 31.08.2107 - in tracked repository)
#' * Route information - still outdated and only 57 ports included (file generated by Jim Corbett, see 2016 NIS-WRAPS meeting notes.
#' * Lloyds port IDs to places, some coordinates may be missing
#' * Date from [@Keller2011], needed for temperature values. 

paths <- list (INVE = "/Users/paul/Box Sync/CU_NIS-WRAPS/170726_sample_info/180314_cs_samples.xlsx",
  CLIM = "/Users/paul/Dropbox/NSF NIS-WRAPS Data/Climate Data\ -\ Ports/allportdata3.xlsx",
  ROUT = "/Users/paul/Box Sync/CU_NIS-WRAPS/170727_port_information/160318_57_connected_ports_DERIVATIVE.xlsx",
  PORT = "/Users/paul/Dropbox/NSF NIS-WRAPS Data/raw data for Mandana/PlacesFile_updated_Aug2017.xlsx",
  TEMP = "/Users/paul/Box Sync/CU_NIS-WRAPS/170727_port_information/170901_Keller_2010_suppl/DDI_696_sm_TableS3.xlsx")
  
#'
#' ## Read in data sources  
#'
#' Reading in the data and printing for verifications
src_heap <- lapply (paths, get_contents)

#' Saving inventory and port data files - in case source dir changes drastically. **Updated to project directory
#' 17.04.2018**
save (src_heap, 
  file = "/Users/paul/Documents/CU_combined/Zenodo/R_Objects/500_10_gather_predictor_tables__input__all.Rdata")

#' Cleaning environment
rm (paths)

#'
#' # Cleaning  data
#'
#' ## Inspecting data structure
#' 
#' To find what needs  to be altered, print the input data structure:
str(src_heap, max.level = 2)

#' 
#' ## Inventory data
#' 
#' Sub- and type setting:
src_heap$INVE <- dplyr::select (src_heap$INVE, c ("PORT", "LATI","LONG"))
src_heap$INVE$LATI <- as.numeric   (src_heap$INVE$LATI)
src_heap$INVE$LONG <- as.numeric   (src_heap$INVE$LONG)
src_heap$INVE$PORT <- as.character (src_heap$INVE$PORT)

#'
#' ## Climate data
#' 
#' Sub- and type setting:
src_heap$CLIM <- dplyr::select(src_heap$CLIM, c("NAME", "ID", "ABBREV",
  "LATDD", "LONGDD", "YR_MEAN_T", "Salinity", "ECOREGION_FINAL", "NorthSouth"))

names (src_heap$CLIM) <- c("PORT", "PID", "COUN", "LATI", "LONG", 
  "TMEAN", "SMEAN", "ECOR", "HEMI")
  
src_heap$CLIM$PORT  <- as.character (src_heap$CLIM$PORT)
src_heap$CLIM$PID   <- as.numeric   (src_heap$CLIM$PID)
src_heap$CLIM$COUN  <- as.character (src_heap$CLIM$COUN)
src_heap$CLIM$LATI  <- as.numeric   (src_heap$CLIM$LATI)
src_heap$CLIM$LONG  <- as.numeric   (src_heap$CLIM$LONG)
src_heap$CLIM$TMEAN <- as.numeric   (src_heap$CLIM$TMEAN)
src_heap$CLIM$SMEAN <- as.numeric   (src_heap$CLIM$SMEAN)
src_heap$CLIM$ECOR  <- as.character (src_heap$CLIM$ECOR)
src_heap$CLIM$HEMI  <- as.character (src_heap$CLIM$HEMI)

#'
#' ## Route data
#' 
#' Sub- and type setting:
src_heap$ROUT <- dplyr::select(src_heap$ROUT, c ("Route_Name", "PortA", "PortALat", 
  "PortALon", "PortB", "PortBLat", "PortBLon",  "Sum_of_Trips"))

names (src_heap$ROUT) <- c("ROUTE", "PRTA", "PALATI", "PALONG", "PRTB", "PBLATI",
  "PBLONG", "TRIPS") # rename

src_heap$ROUT$ROUTE  <- as.character (src_heap$ROUT$ROUTE)
src_heap$ROUT$PRTA   <- as.numeric   (src_heap$ROUT$PRTA)
src_heap$ROUT$PALATI <- as.numeric   (src_heap$ROUT$PALATI)
src_heap$ROUT$PALONG <- as.numeric   (src_heap$ROUT$PALONG)
src_heap$ROUT$PRTB   <- as.numeric   (src_heap$ROUT$PRTB)
src_heap$ROUT$PBLATI <- as.numeric   (src_heap$ROUT$PBLATI)
src_heap$ROUT$PBLONG <- as.numeric   (src_heap$ROUT$PBLONG)
src_heap$ROUT$TRIPS  <- as.numeric   (src_heap$ROUT$TRIPS)

#'
#' ## Port information
#' 
#' Sub- and type setting:
src_heap$PORT <- dplyr::select (src_heap$PORT, c ("PLACE\ ID", "PLACE\ NAME",
  "COUNTRY\ CODE", "LATITUDE\ DECIMAL", "LONGITUDE\ DECIMAL")) 
  
names (src_heap$PORT) <- c("PID", "PORT", "COUN", "LATI", "LONG")

src_heap$PORT$PID  <- as.numeric   (src_heap$PORT$PID)
src_heap$PORT$PORT <- as.character (src_heap$PORT$PORT)
src_heap$PORT$COUN <- as.character (src_heap$PORT$COUN)
src_heap$PORT$LATI <- as.numeric   (src_heap$PORT$LATI)
src_heap$PORT$LONG <- as.numeric   (src_heap$PORT$LONG)

#'
#' ## Temperature and salinity data from [@Keller2011]
#' 
#' I am omitting type setting since all types are set well. Sub setting:
src_heap$TEMP <- dplyr::select (src_heap$TEMP, c ("PortName", "Country",
  "Latitude", "Longitude", "MinTemp", "MaxTemp", "AnnualTemp", "Salinity",
  "TempSource", "SalSource")) 

names (src_heap$TEMP) <- c ("PORT", "COUN", "LATI", "LONG", "TMIN", "TMAX",
  "TMEN", "SMEN", "TSRC", "SSRC")

#'
#' ## Inspecting cleaned tables
#'
#' Just getting the data structure here:
str(src_heap, max.level = 2)

#'
#' # Writing data to disc
#'
#' Saving structure for subsequent script or future reference. **Updated to project directory
#' 17.04.2018**
save (src_heap,
 file = "/Users/paul/Documents/CU_combined/Zenodo/R_Objects/500_10_gather_predictor_tables__output__all.Rdata")

#' # Session info
#' 
#' The code and output in this document were tested and generated in the 
#' following computing environment:
#+ echo=FALSE
sessionInfo()

#' # References 
