#' ---
#' title: "Calculating environmental distances between samples"
#' author: "Paul Czechowski"
#' date: "September 1st, 2017"
#' output: pdf_document
#' toc: true
#' highlight: zenburn
#' bibliography: ./references_2.bib
#' ---
#'
#' # Preface
#' 
#' This script re-creates calculations to rank international ports based on
#' similarity [@Keller2011]. There is no code associated with that manuscript,
#' making it hard recreate those analyses. Here, the formalized expression
#' is recreated, which corresponds to the statement _“As a measure of environmental
#' distance to the GGLE we calculated the Euclidean distance, in four-dimensional
#' space (salinity plus three temperature dimensions), from all global ports to
#' the average salinity and temperature values of the 164 ports located within 
#' the GGLE”_ (page 96). This script can be rendered by
#' calling `rmarkdown::render ("/Users/paul/Documents/CU_combined/Github/500_20_get_environmental_distances.R")`.
#' 
#' # Prerequisites to run this code
#'
#' Reads file `/Users/paul/Documents/CU_combined/Zenodo/R_Objects/500_10_gather_predictor_tables__output__all.Rdata`
#' was generated by script `/Users/paul/Documents/CU_combined/Github/500_10_gather_predictor_tables.R`, which was
#' first committed as `7b5048937ae347fc46b16fb369e1d3f1a91ce874` in general R script folder. 
#' 
#' # Environment preparation
#'
#' ## Package loading and cleaning of workspace
#+ message=FALSE, results='hide'
library (dplyr)       # data wrangling
library (vegan)       # distance calculations
library (reshape2)    # plotting, table manipulation
library (ggplot2)     # plotting

#'
#' ## Flushing buffer
#' 

rm(list=ls()) # This is for safety only.

#' 
#' ## Functions
#'

# There are no functions yet. 

#' # Formatting input data
#' 
#' ## Data import
#' 
#' Needed data is stored in a list of data frames called `src_heap`. Loading
#' and checking it's loaded.

load (
  file = "/Users/paul/Box Sync/CU_NIS-WRAPS/170815_R_storage/170830_10_cleanup_tables__output__all.Rdata"
  )

exists ("src_heap")

#' 
#' ## Inspecting raw data
#' 
#' The raw data is here (still), and types are set appropriately:

src_heap$TEMP[c("TMIN", "TMAX", "TMEN", "SMEN")]

#' 
#' Let's look at the distribution of the raw data

molten <- melt(src_heap$TEMP[c("TMIN", "TMAX", "TMEN", "SMEN")])
ggplot(molten, aes(x=value, fill=variable)) + geom_density(alpha=0.25)

#' 
#' # Calculating port distances
#' 
#' “As a measure of environmental distance [...] we calculated the 
#' Euclidean distance, in four-dimensional space (salinity plus three 
#' temperature dimensions)" (on scaled and centered data) [@Keller2011]. 
#' I will scale and center before I calculate distances.
#' 
#' ## Scaling and centring 
#' 
scaled_heap <- as_tibble (scale (src_heap$TEMP[c("TMIN", "TMAX", "TMEN", "SMEN")]))

#'
#' ## Inspecting scaled and centered data
#' 
#' This can be inspected:
molten <- melt(scaled_heap)
ggplot(molten, aes(x=value, fill=variable)) + geom_density(alpha=0.25)

#'
#' ## Generating a distance matrix
#' 
#' I can also easily calculate a distance matrix as in [@Keller2011]:

# head() for debugging only - if a small test data set is needed
eucl_heap <- dist (scaled_heap, method = "euclidean", diag = TRUE, upper = TRUE)

#' 
#' ## Exporting the matrix
#' 
save (eucl_heap,
 file = "/Users/paul/Box Sync/CU/170815_R_storage/170901_20_calculate_distances__output.Rdata")

#' # Session info
#' 
#' The code and output in this document were tested and generated in the 
#' following computing environment:
#+ echo=FALSE
sessionInfo()

#' # References
